### ISSUE TITLE
Blank page after first install

### ISSUE THREAD

**Issue by pocky** [openl10n/openl10n#100]
Hello,
After install and setup, I have a blank page with this error:
`TypeError: Backbone.Wreqr is undefined in app.js:9464:21` (Firefox)

Any idea?
Thx!

**Comment by xavismeh** [comment]
Same in here

**Comment by MattKetmo** [comment]
Unfortunatly there is no lock file with npm, so I fixed the backbone version manually via 5daf0c7.
Should be fixed now.

**Comment by pocky** [comment]
It works!
Thanks for your time and (maybe) see you later ;)
