### ISSUE TITLE
Heroku support

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n#75]
Make this app compliant with Heroku (via a `Procfile`), and then add a [Deploy on Heroku button](https://blog.heroku.com/archives/2014/8/7/heroku-button) in the Readme.

Needs:
- PHP
- MySQL
- Init config (parameter.yml)
- Composer install
- Create database
- Db migrations
- Create user ?
- Node/gulp/Sass & cie ?

**Comment by stof** [comment]
For heroku, I suggest using postgres rather than MySQL given that heroku themselves provide a Postgres addon while MySQL requires using a separate service
