### ISSUE TITLE
PHP 5.6 deprecated warning HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n#87]
_PHP 5.6: “Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.”_

See https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/

**Comment by stof** [comment]
AFAICT, there is nothing you can do here (assuming you don't use it yourselves). It needs to be fixed in the php.ini file itself
